### ISSUE TITLE
No sounds when using LCMaxSoundsFix

### ISSUE THREAD

**Issue by Yoshi72** [FHAUKEM/LCKartHornMod#1]
When LCMaxSoundsFix is installed, the horns just won't play any sounds.
The console seem to be assigning each horn a new sound just fine, and there are no errors either.

Mod Link:
https://thunderstore.io/c/lethal-company/p/Hardy/LCMaxSoundsFix/

This issue happens even in a minimalistic modpack with only LCMaxSoundsFix and this mod and their dependencies.

**Comment by FHAUKEM** [comment]
Apparently, the mod author of LCMaxSoundsFix has fixed it from their side. Everything should work together now!

Closing this. If something is still off, feel free to reopen, make a new issue, or send a message in the thread on Discord.
